site_name: Fragments of Temuair

theme:
  name: material
  custom_dir: overrides
  palette:
          primary: blue grey
          accent: blue
  icon:
          logo: material/wizard-hat
  favicon: assets/wizard-hat.png

extra_css:
        - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Resources: resources.md
  - Classes:
          - Overview: classes/overview.md
          - Subbing: classes/subbing.md
          - Specializations: classes/specializations.md
  - Quests: quests/overview.md
  - Hunting: hunting.md
  - Knowledge:
          - Religion: knowledge/religion.md
          - Backpack: knowledge/backpack.md
          - Armour Dyeing: knowledge/armour_dyeing.md
          - Temuair Marketplace: knowledge/marketplace.md
          - Auction House: knowledge/auction_house.md
          - Labour: knowledge/labour.md
          - Books: knowledge/books.md
          - Spell Panes: knowledge/spell_panes.md
          - Sapphire Stream: knowledge/sapphire_stream.md
          - Tagor Training: knowledge/tagor_training.md
  - Crafting:
          - Upgrades: crafting/upgrades.md
          - Fragments: crafting/fragments.md
          - Armour Crafting: crafting/armour_crafting.md
          - Gem Smithing: crafting/gem_smithing.md
          - Ring Smithing: crafting/ring_smithing.md
          - Staff Crafting: crafting/staff_crafting.md
          - Weapon Smithing: crafting/weapon_smithing.md
          - Enchanting: crafting/enchanting.md
  - Spells:
          - Priest: spells/priest.md
  - Weapons:
          - All: weapons/all.md
          - Warrior: weapons/warrior.md
          - Priest: weapons/priest.md
          - Wizard: weapons/wizard.md
          - Rogue: weapons/rogue.md
  - Maps:
          - Mileth Crypt: maps/mileth_crypt.md
